export interface SeedDirectoryListing {
  name: string
  slug: string
  category_slug: string
  dzongkhag_slug?: string
  description: string
  address?: string
  phone?: string[]
  email?: string
  website?: string
  established_year?: number
  latitude?: number
  longitude?: number
}

export const directoryListings: SeedDirectoryListing[] = [
  // Education
  {
    name: 'Royal University of Bhutan',
    slug: 'royal-university-of-bhutan',
    category_slug: 'colleges-universities',
    dzongkhag_slug: 'thimphu',
    description: 'Bhutan\'s first and only national university, established by royal charter of King Jigme Singye Wangchuck. It operates as a federated system of 10 constituent colleges spread across the country, enrolling approximately 10,000 students in programs spanning engineering, education, natural resources, IT, traditional medicine, and management. The King of Bhutan serves as Chancellor, and the university is a member of the Association of Commonwealth Universities.',
    website: 'https://www.rub.edu.bt',
    established_year: 2003,
    latitude: 27.4728, longitude: 89.6390,
  },
  {
    name: 'Sherubtse College',
    slug: 'sherubtse-college',
    category_slug: 'colleges-universities',
    dzongkhag_slug: 'trashigang',
    description: 'The oldest and largest institution of higher learning in Bhutan, tracing its origins to a public school founded in 1968 with Jesuit assistance from Darjeeling. Initially affiliated with Delhi University before joining RUB in 2003, it offers bachelor\'s degrees in arts, sciences, commerce, development economics, and environmental science to over 1,500 students. Its name means "peak of knowledge" in Dzongkha, and the hilltop campus sits at approximately 2,000 meters elevation.',
    address: 'Kanglung, Trashigang',
    established_year: 1983,
    latitude: 27.2833, longitude: 91.5167,
  },
  {
    name: 'College of Science and Technology',
    slug: 'college-of-science-and-technology',
    category_slug: 'colleges-universities',
    dzongkhag_slug: 'chhukha',
    description: 'Bhutan\'s premier engineering institution and a constituent college of the Royal University of Bhutan. It offers bachelor\'s degrees in civil, electrical, and electronics engineering, information technology, and architecture — the only college in Bhutan granting accredited engineering degrees at the undergraduate level. CST enrolls approximately 1,000 students and has been instrumental in building Bhutan\'s domestic technical workforce.',
    address: 'Rinchending, Phuentsholing',
    website: 'https://www.cst.edu.bt',
    established_year: 2001,
    latitude: 26.8585, longitude: 89.3830,
  },
  {
    name: 'Jigme Namgyel Engineering College',
    slug: 'jigme-namgyel-engineering-college',
    category_slug: 'colleges-universities',
    dzongkhag_slug: 'samdrup-jongkhar',
    description: 'Bhutan\'s oldest technical institution, originally established in 1974 as the Royal Bhutan Polytechnic with Swiss Helvetas development assistance. Renamed in 1991 in honor of the father of Bhutan\'s first king, it was upgraded to a full engineering college and RUB constituent member in 2012. JNEC offers diploma and bachelor\'s degree programs in civil, electrical, and mechanical engineering, having trained generations of engineers who built much of Bhutan\'s road and hydropower infrastructure.',
    address: 'Dewathang, Samdrup Jongkhar',
    established_year: 1974,
  },
  {
    name: 'Royal Institute of Management',
    slug: 'royal-institute-of-management',
    category_slug: 'colleges-universities',
    dzongkhag_slug: 'thimphu',
    description: 'Bhutan\'s principal institution for management education and public administration training, created with support from the Royal Civil Service Commission to develop governance capacity. RIM offers postgraduate diplomas in public administration and national development management, an MBA in collaboration with international partners, and executive development programs for government officials. The institute has trained thousands of civil servants in Gross National Happiness-informed policy design.',
    address: 'Semtokha, Thimphu',
    website: 'https://www.rim.edu.bt',
    established_year: 1986,
    latitude: 27.4412, longitude: 89.6695,
  },

  // Healthcare
  {
    name: 'Jigme Dorji Wangchuck National Referral Hospital',
    slug: 'jdwnrh',
    category_slug: 'hospitals',
    dzongkhag_slug: 'thimphu',
    description: 'Named after the third King of Bhutan, JDWNRH is the country\'s largest and only tertiary-care hospital, serving as the apex of Bhutan\'s free national healthcare system with approximately 381 beds. It offers over 20 specialty departments including cardiology, oncology, neurology, orthopedics, and nephrology, handling referrals from all 20 dzongkhags. The hospital underwent a major expansion with Indian government assistance and serves as the primary teaching hospital affiliated with the Khesar Gyalpo University of Medical Sciences.',
    address: 'Thimphu',
    phone: ['+975-2-322496'],
    established_year: 1972,
    latitude: 27.4689, longitude: 89.6414,
  },
  {
    name: 'Central Regional Referral Hospital Gelephu',
    slug: 'central-regional-referral-hospital-gelephu',
    category_slug: 'hospitals',
    dzongkhag_slug: 'sarpang',
    description: 'The secondary and tertiary referral center for Bhutan\'s six south-central dzongkhags — Sarpang, Tsirang, Dagana, Zhemgang, Trongsa, and Bumthang — with a capacity of approximately 150 beds. It provides general medicine, surgery, obstetrics and gynecology, pediatrics, orthopedics, and emergency services as part of Bhutan\'s constitutionally guaranteed free healthcare system. The hospital has gained strategic importance with the development of Gelephu Mindfulness City and is slated for significant expansion.',
    address: 'Gelephu, Sarpang',
    established_year: 1980,
  },
  {
    name: 'Eastern Regional Referral Hospital',
    slug: 'eastern-regional-referral-hospital',
    category_slug: 'hospitals',
    dzongkhag_slug: 'mongar',
    description: 'The primary referral facility for Bhutan\'s six eastern dzongkhags — Mongar, Lhuentse, Trashigang, Trashi Yangtse, Pemagatshel, and Samdrup Jongkhar — serving a catchment population of approximately 170,000. The hospital has around 180 beds and provides specialty services including general surgery, obstetrics, pediatrics, ophthalmology, ENT, and diagnostic imaging. It plays a critical role in healthcare equity for eastern Bhutan, one of the country\'s most remote and underserved regions.',
    address: 'Mongar Town',
    established_year: 1979,
  },
  {
    name: 'National Traditional Medicine Hospital',
    slug: 'national-traditional-medicine-hospital',
    category_slug: 'traditional-medicine',
    dzongkhag_slug: 'thimphu',
    description: 'The flagship institution for Sowa Rigpa (Buddhist traditional medicine), making Bhutan one of the few countries to formally integrate indigenous healing into its national healthcare system. The hospital offers traditional diagnosis through pulse reading and urinalysis, herbal medicine compounding from over 300 medicinal plant species, moxibustion, acupuncture, and traditional hot-stone baths — all provided free of charge. It also houses the Traditional Medicine Research and Development unit and serves as the hub for a nationwide network of traditional medicine units in all 20 dzongkhags.',
    address: 'Kawajangsa, Thimphu',
    established_year: 1967,
    latitude: 27.4751, longitude: 89.6389,
  },

  // Religious Sites
  {
    name: 'Taktsang Palphug Monastery (Tiger\'s Nest)',
    slug: 'taktsang-monastery',
    category_slug: 'monasteries',
    dzongkhag_slug: 'paro',
    description: 'Bhutan\'s most iconic sacred site, clinging to a sheer cliff face 900 meters above the Paro Valley floor at 3,120 meters elevation. Built in 1692 around the cave where Guru Padmasambhava is believed to have flown on the back of a tigress and meditated for three years, three months, three weeks, three hours, and three minutes in the 8th century. Severely damaged by fire in 1998 and meticulously restored by 2005 under royal patronage, visitors reach the monastery via a steep 2-3 hour hike through blue pine forest.',
    address: 'Taktsang Trail, Paro',
    established_year: 1692,
    latitude: 27.4913, longitude: 89.3634,
  },
  {
    name: 'Tashichho Dzong',
    slug: 'tashichho-dzong',
    category_slug: 'dzongs',
    dzongkhag_slug: 'thimphu',
    description: 'Originally constructed by Zhabdrung Ngawang Namgyal, the unifier of Bhutan, Tashichho Dzong ("Fortress of the Glorious Religion") houses the throne room of the King, offices of several ministries, and the secretariat. Extensively rebuilt in 1962-1969 under the Third King in traditional style without nails or architectural plans. Its northern section serves as the summer residence of the Central Monastic Body, hosting approximately 2,000 monks, and it is the site of the spectacular annual Thimphu Tshechu festival.',
    address: 'Thimphu',
    established_year: 1641,
    latitude: 27.4864, longitude: 89.6391,
  },
  {
    name: 'Punakha Dzong',
    slug: 'punakha-dzong',
    category_slug: 'dzongs',
    dzongkhag_slug: 'punakha',
    description: 'Built by Zhabdrung Ngawang Namgyal at the strategic confluence of the Pho Chhu (Father River) and Mo Chhu (Mother River), Punakha Dzong is the second oldest dzong in Bhutan and widely regarded as the most beautiful. It houses sacred relics including the Rangjung Kharsapani, served as the capital until 1955, and remains the winter residence of the Central Monastic Body and the site where every Bhutanese king has been crowned, including the current Fifth King in 2008. The massive structure features three courtyards, a six-story central tower, and a cantilevered wooden bridge spanning the Mo Chhu.',
    address: 'Punakha',
    established_year: 1637,
    latitude: 27.5911, longitude: 89.8625,
  },
  {
    name: 'Trongsa Dzong',
    slug: 'trongsa-dzong',
    category_slug: 'dzongs',
    dzongkhag_slug: 'trongsa',
    description: 'The largest dzong in Bhutan, commanding a strategic ridge overlooking the Mangde Chhu gorge at central Bhutan\'s narrowest point, historically controlling all east-west travel through the kingdom. The ancestral seat of the Wangchuck dynasty — both the first and second kings ruled from Trongsa before ascending the throne, and by tradition every crown prince must first serve as Trongsa Penlop (governor). Its complex of over 30 temples and administrative offices cascades down the mountainside, and the adjacent Ta Dzong was converted into the Tower of Trongsa Royal Heritage Museum in 2008.',
    address: 'Trongsa',
    established_year: 1644,
    latitude: 27.5004, longitude: 90.5066,
  },
  {
    name: 'Gangtey Monastery',
    slug: 'gangtey-monastery',
    category_slug: 'monasteries',
    dzongkhag_slug: 'wangdue-phodrang',
    description: 'Founded by Gyalse Pema Thinley, grandson and reincarnation of the treasure-revealer Pema Lingpa, Gangtey Goenpa is the largest Nyingmapa monastery in western Bhutan. It crowns a forested hillock overlooking the glacial Phobjikha Valley at approximately 2,900 meters, one of the few remaining glacial valleys in the eastern Himalayas. The valley below is the winter roosting ground for 300-500 endangered black-necked cranes that migrate from Tibet each October, and the monastery hosts the annual Black-Necked Crane Festival in November.',
    address: 'Phobjikha Valley, Wangdue Phodrang',
    established_year: 1613,
    latitude: 27.4633, longitude: 90.1617,
  },

  // Business
  {
    name: 'Druk Air Corporation',
    slug: 'druk-air',
    category_slug: 'large-enterprises',
    dzongkhag_slug: 'paro',
    description: 'Bhutan\'s state-owned national flag carrier (IATA: KB), wholly owned by the Royal Government. It operates a fleet of Airbus A319 and A320 aircraft serving Bangkok, Delhi, Kathmandu, Kolkata, Dhaka, Singapore, and Mumbai from Paro International Airport. As one of only two airlines certified to land in Bhutan\'s challenging mountain-ringed valley airport, Druk Air is the primary gateway for the country\'s tourism industry.',
    address: 'Nemeyzampa, Paro',
    phone: ['+975-8-271856'],
    website: 'https://www.drukair.com.bt',
    email: 'callcenter@drukair.com.bt',
    established_year: 1981,
  },
  {
    name: 'Bhutan Airlines',
    slug: 'bhutan-airlines',
    category_slug: 'large-enterprises',
    dzongkhag_slug: 'paro',
    description: 'Bhutan\'s first private airline (IATA: B3), owned by the Tashi Group, one of Bhutan\'s largest private conglomerates. Operating Airbus A319 aircraft from Paro International Airport, it serves routes to Bangkok, Kolkata, Kathmandu, and Delhi, providing competition on routes previously monopolized by Druk Air. The airline has been instrumental in increasing seat capacity into Bhutan and supporting the growth of the tourism sector.',
    website: 'https://www.bhutanairlines.bt',
    established_year: 2013,
  },
  {
    name: 'Bank of Bhutan',
    slug: 'bank-of-bhutan',
    category_slug: 'banks-finance',
    dzongkhag_slug: 'thimphu',
    description: 'Bhutan\'s largest and oldest commercial bank, originally established as a joint venture between the Royal Government and the State Bank of India. With branches in all 20 dzongkhags and over 30 offices nationwide, it offers retail and corporate banking, agricultural and commercial loans, foreign exchange, and remittances. The bank pioneered ATM and mobile banking in the country and plays a critical role in financial inclusion across Bhutan\'s largely rural population.',
    address: 'Norzin Lam, Thimphu',
    phone: ['+975-2-322767'],
    website: 'https://www.bob.bt',
    established_year: 1968,
    latitude: 27.4728, longitude: 89.6365,
  },
  {
    name: 'Bhutan National Bank',
    slug: 'bhutan-national-bank',
    category_slug: 'banks-finance',
    dzongkhag_slug: 'thimphu',
    description: 'Bhutan\'s first private sector commercial bank, initially established as a joint venture with the Bank of Ceylon. It operates over 30 branches and extension counters across the country, offering retail banking, corporate loans, trade finance, and digital banking services. Listed on the Royal Securities Exchange of Bhutan, BNB has played a key role in modernizing Bhutan\'s financial sector through innovations in internet and mobile banking.',
    address: 'Norzin Lam, Thimphu',
    website: 'https://www.bnb.bt',
    established_year: 1996,
  },
  {
    name: 'Druk Green Power Corporation',
    slug: 'druk-green-power',
    category_slug: 'large-enterprises',
    dzongkhag_slug: 'thimphu',
    description: 'A state-owned enterprise under Druk Holding and Investments that manages Bhutan\'s hydropower assets — the backbone of the national economy accounting for roughly 30% of government revenue and over 70% of export earnings. DGPC operates four major plants: Chhukha (336 MW), Kurichhu (60 MW), Basochhu (64 MW), and Tala (1,020 MW), with a combined installed capacity exceeding 1,480 MW exported primarily to India. New mega-projects including Punatsangchhu-I and Punatsangchhu-II will more than double generation capacity upon completion.',
    address: 'Thimphu',
    website: 'https://www.drukgreen.bt',
    established_year: 2008,
  },
  {
    name: 'TashiCell',
    slug: 'tashicell',
    category_slug: 'telecom',
    dzongkhag_slug: 'thimphu',
    description: 'Bhutan\'s second mobile telecommunications operator, launched by the Tashi Group (Tashi InfoComm Limited) and breaking the monopoly previously held by state-owned B-Mobile (Bhutan Telecom). It provides 2G, 3G, and 4G LTE mobile services with coverage across all 20 dzongkhags. As a subsidiary of Bhutan\'s largest private conglomerate — with interests spanning airlines, hotels, banking, and media — TashiCell has driven competition that improved service quality and reduced prices for consumers.',
    address: 'Thimphu',
    website: 'https://www.tashicell.com',
    established_year: 2008,
  },

  // Entertainment & Media
  {
    name: 'Travellers and Magicians',
    slug: 'travellers-and-magicians',
    category_slug: 'bhutanese-films',
    dzongkhag_slug: 'bumthang',
    description: 'Directed by Khyentse Norbu (Dzongsar Jamyang Khyentse Rinpoche), this 2003 film is the first feature shot entirely in Bhutan, filmed on location in the Bumthang and Ura valleys. The story follows a restless village official dreaming of emigrating to America, interwoven with a cautionary folk tale narrated by a traveling monk. It premiered at the 2003 Cannes Film Festival in the Directors\' Fortnight section and screened at Toronto and Venice, introducing international audiences to Bhutan\'s landscapes and storytelling traditions.',
    established_year: 2003,
  },
  {
    name: 'The Cup (Phörpa)',
    slug: 'the-cup-phorpa',
    category_slug: 'bhutanese-films',
    description: 'Directed by Khyentse Norbu, The Cup is widely regarded as the first Bhutanese feature film and was Bhutan\'s first submission to the Academy Awards for Best Foreign Language Film. Based on a true story, the comedy-drama follows young Tibetan Buddhist monks in a monastery in exile who become obsessed with the 1998 FIFA World Cup final between France and Brazil. Shot at Chokling Monastery in Bir, India, with non-professional monk actors, it grossed over $1 million at the US box office and screened at Cannes, Toronto, and dozens of international festivals.',
    established_year: 1999,
  },
  {
    name: 'Hema Hema: Sing Me a Song While I Wait',
    slug: 'hema-hema',
    category_slug: 'bhutanese-films',
    description: 'Directed by Khyentse Norbu, this experimental drama explores identity, ego, and liberation through a mysterious forest ritual where all participants don masks, erasing social distinctions of rank, gender, and age. The film premiered at the 73rd Venice International Film Festival in the Venice Days section, making it one of the few Bhutanese films to screen at a major European festival. Drawing deeply from Buddhist philosophy on the nature of the self, it is considered Khyentse Norbu\'s most artistically ambitious work.',
    established_year: 2016,
  },
  {
    name: 'Bhutan Broadcasting Service',
    slug: 'bhutan-broadcasting-service',
    category_slug: 'media-houses',
    dzongkhag_slug: 'thimphu',
    description: 'Bhutan\'s sole public broadcaster, originally established as the NYAB radio station in 1973. BBS launched Bhutan\'s first television channel on June 2, 1999 — coinciding with the Silver Jubilee of King Jigme Singye Wangchuck\'s coronation and making Bhutan one of the last countries in the world to introduce television. It operates two radio channels (Dzongkha/Sharchop and English/Nepali) alongside its TV channel, providing news, cultural programming, and live coverage of national events in four languages.',
    address: 'Chubachu, Thimphu',
    phone: ['+975-2-323071'],
    website: 'https://www.bbs.bt',
    established_year: 1973,
    latitude: 27.4743, longitude: 89.6366,
  },
  {
    name: 'Kuensel',
    slug: 'kuensel',
    category_slug: 'media-houses',
    dzongkhag_slug: 'thimphu',
    description: 'Bhutan\'s oldest and most widely circulated newspaper, founded as a government bulletin in 1967. It evolved from a monthly internal newsletter to a weekly and later daily publication, gaining editorial independence when corporatized as Kuensel Corporation Limited in 1992. Published in English, Dzongkha, and Nepali editions, its online edition at kuenselonline.com is one of the most-read English-language news sources on Bhutan worldwide, and the paper played a pivotal role during Bhutan\'s transition to constitutional monarchy in 2008.',
    address: 'Thimphu',
    website: 'https://www.kuenselonline.com',
    established_year: 1967,
  },

  // Tourism
  {
    name: 'Jigme Dorji National Park',
    slug: 'jigme-dorji-national-park',
    category_slug: 'national-parks',
    dzongkhag_slug: 'gasa',
    description: 'Bhutan\'s largest protected area, covering 4,349 km² across Gasa, Paro, Thimphu, and Punakha districts, with elevations from 1,400 m to over 7,000 m including the sacred peak Jomolhari (7,326 m). The park harbours 37 mammal species and over 300 bird species including snow leopards, Bengal tigers, takin, blue sheep, red pandas, and the critically endangered white-bellied heron. Named after Prime Minister Jigme Palden Dorji, it features the Jomolhari Trek and the northern section of the Snowman Trek, with biological corridors connecting to Wangchuck Centennial and Jigme Singye Wangchuck national parks.',
    established_year: 1974,
  },
  {
    name: 'Royal Manas National Park',
    slug: 'royal-manas-national-park',
    category_slug: 'national-parks',
    dzongkhag_slug: 'sarpang',
    description: 'Bhutan\'s oldest protected area, originally established as Manas Wildlife Sanctuary in 1966 and covering 1,057 km² across Sarpang, Zhemgang, and Pemagatshel districts with elevations from 150 m to 2,900 m. Contiguous with India\'s Manas National Park to form a transboundary conservation complex of approximately 2,800 km², it supports over 900 plant species, 365 bird species, and 85 mammal species including Bengal tigers, Asian elephants, golden langurs, pygmy hogs, and hispid hares. Recognized by UNESCO in 2008 for its global conservation significance within the eastern Himalayan biodiversity hotspot.',
    established_year: 1966,
  },
  {
    name: 'Jigme Singye Wangchuck National Park',
    slug: 'jigme-singye-wangchuck-national-park',
    category_slug: 'national-parks',
    dzongkhag_slug: 'trongsa',
    description: 'A 1,730 km² protected area spanning the Black Mountains range with elevations from 670 m to 4,925 m across Trongsa, Zhemgang, Sarpang, and Wangdue Phodrang districts. Originally designated as Black Mountain National Park in 1995 and renamed in 2008, it serves as Bhutan\'s most critical biological corridor — the only unbroken north-south habitat link between Jigme Dorji and Royal Manas national parks. The park boasts over 450 bird species, one of the highest avian densities per unit area in Asia, and the adjacent Phobjikha Valley is a vital wintering ground for the endangered black-necked crane.',
    established_year: 1995,
  },
  {
    name: 'Snowman Trek',
    slug: 'snowman-trek',
    category_slug: 'trekking-routes',
    dzongkhag_slug: 'gasa',
    description: 'Widely regarded as one of the most difficult long-distance treks in the world, this 356 km route traverses northern Bhutan over 25-30 days, crossing eleven passes above 4,500 m with a completion rate estimated at less than 50% due to early snowfall, altitude sickness, and exhaustion. The trek passes through the remote communities of Lingshi, Laya, and Lunana, offering encounters with yak-herding cultures and views of peaks exceeding 7,000 m along the Tibetan border. The trekking window is limited to September and October, requiring pack animal support with crews of 15-25 people.',
  },
  {
    name: 'Druk Path Trek',
    slug: 'druk-path-trek',
    category_slug: 'trekking-routes',
    dzongkhag_slug: 'paro',
    description: 'One of Bhutan\'s most popular treks, this 5-day route connects Paro to Thimphu across a ridgeline reaching approximately 4,200 m, passing through blue pine and rhododendron forests with panoramic views of Jomolhari and Jichu Drake. The trail passes several high-altitude alpine lakes including Jimilangtso and Janetsho, sacred to local communities and surrounded by dwarf rhododendron and juniper scrub. Best undertaken March-June or September-November, the trek is accessible to moderately fit hikers with chances of spotting Himalayan monal pheasants and musk deer.',
  },
  {
    name: 'Gasa Tshachu',
    slug: 'gasa-tshachu',
    category_slug: 'hot-springs',
    dzongkhag_slug: 'gasa',
    description: 'A cluster of natural hot spring pools along the Mo Chhu river at approximately 2,200 m elevation within Jigme Dorji National Park. The mineral-rich waters contain calcium, sodium, and trace sulphur compounds at temperatures between 40-50°C, traditionally believed to relieve arthritis, skin ailments, and body pain. Set in a forested river gorge accessible by a one-hour walk from Gasa town, Bhutanese visitors have bathed here for centuries, often combining visits with pilgrimages to nearby Gasa Dzong.',
    address: 'Gasa',
  },

  // Infrastructure
  {
    name: 'Paro International Airport',
    slug: 'paro-international-airport',
    category_slug: 'airports',
    dzongkhag_slug: 'paro',
    description: 'Bhutan\'s sole international airport (IATA: PBH), situated at 2,235 m elevation in a deep valley of the Paro Chhu river, surrounded by peaks reaching 5,500 m. Considered one of the world\'s most challenging commercial airports, it requires pilots to hold a special qualification to navigate the steep, winding visual approach — only a handful of pilots worldwide are certified to land here. The single runway serves Druk Air and Bhutan Airlines with flights to destinations across India, Nepal, Bangladesh, Thailand, and Singapore.',
    address: 'Paro',
    established_year: 1983,
    latitude: 27.4033, longitude: 89.4246,
  },
  {
    name: 'Tala Hydroelectric Project',
    slug: 'tala-hydroelectric-project',
    category_slug: 'hydropower-plants',
    dzongkhag_slug: 'chhukha',
    description: 'Bhutan\'s largest hydroelectric power station with an installed capacity of 1,020 MW generated by six Francis turbines on the Wang Chhu river. Built as an India-Bhutan bilateral project, it generates around 4,865 GWh annually, with the vast majority exported to India and accounting for a significant share of Bhutan\'s total revenue. The underground powerhouse is fed by a 22 km headrace tunnel from the Tala dam, making it one of the largest underground hydropower projects in South Asia.',
    established_year: 2007,
  },
  {
    name: 'Gelephu Mindfulness City Airport',
    slug: 'gelephu-mindfulness-city-airport',
    category_slug: 'airports',
    dzongkhag_slug: 'sarpang',
    description: 'A new international airport under construction as a cornerstone of the Gelephu Mindfulness City (GMC), a 1,000 sq km Special Administrative Region announced by King Jigme Khesar Namgyel Wangchuck in December 2023. Designed to serve as Bhutan\'s second international gateway complementing Paro, it will feature a runway capable of handling wide-body aircraft. The GMC master plan by Danish architect Bjarke Ingels Group (BIG) aims to attract foreign investment, tech industries, and sustainable tourism while preserving Bhutan\'s Gross National Happiness philosophy.',
    address: 'Gelephu, Sarpang',
  },

  // Municipalities
  {
    name: 'Thimphu Thromde',
    slug: 'thimphu-thromde',
    category_slug: 'thromdes',
    dzongkhag_slug: 'thimphu',
    description: 'The capital and largest city of Bhutan with an estimated population exceeding 115,000, situated at 2,334 m elevation in the Wang Chhu river valley. A Class A Thromde governed by an elected Thrompon (mayor), it houses Tashichho Dzong (seat of government), the Supreme Court, and the National Assembly, accounting for a significant share of Bhutan\'s GDP through government services, tourism, and a growing IT sector. Unique among world capitals, Thimphu has no traffic lights, using traffic police to manage its increasingly congested streets.',
    latitude: 27.4728, longitude: 89.6390,
  },
  {
    name: 'Phuentsholing Thromde',
    slug: 'phuentsholing-thromde',
    category_slug: 'thromdes',
    dzongkhag_slug: 'chhukha',
    description: 'Bhutan\'s commercial capital and primary trade gateway, situated at just 300 m elevation on the border with the Indian town of Jaigaon in West Bengal. This Class A Thromde with a population of approximately 30,000 handles over 80% of Bhutan\'s bilateral trade with India, including imports of fuel, construction materials, and consumer goods. Home to major financial institutions, the Bhutan Chamber of Commerce, and industrial estates, it is the main entry point for overland travelers and commercial traffic.',
    latitude: 26.8585, longitude: 89.3830,
  },
  {
    name: 'Gelephu Thromde',
    slug: 'gelephu-thromde',
    category_slug: 'thromdes',
    dzongkhag_slug: 'sarpang',
    description: 'A southern border town in Sarpang district with a population of approximately 10,000, adjacent to the Indian state of Assam at 300 m elevation. In December 2023, King Jigme Khesar designated a 1,000 sq km area centered on Gelephu as the Gelephu Mindfulness City, a Special Administrative Region envisioned as an international economic hub with its own governance framework, tax structure, and international airport. The town is home to the Central Regional Referral Hospital and its subtropical climate makes it strategically suited for large-scale development.',
  },
  {
    name: 'Samdrup Jongkhar Thromde',
    slug: 'samdrup-jongkhar-thromde',
    category_slug: 'thromdes',
    dzongkhag_slug: 'samdrup-jongkhar',
    description: 'An eastern border town and Class A Thromde with a population of approximately 8,000, serving as the primary trade gateway between eastern Bhutan and India\'s Assam state at around 200 m elevation. The town is a commercial hub for the six eastern dzongkhags, with a busy cross-border market trading in agricultural products, textiles, and consumer goods. It also serves as the eastern entry point for tourists and connects to Trashigang and the rest of eastern Bhutan via the national highway network.',
  },

  // Government
  {
    name: 'National Assembly of Bhutan',
    slug: 'national-assembly-of-bhutan',
    category_slug: 'district-offices',
    dzongkhag_slug: 'thimphu',
    description: 'The lower house of Bhutan\'s bicameral Parliament established under the 2008 Constitution, consisting of 47 elected members representing single-member constituencies across all 20 dzongkhags through a first-past-the-post system. The Assembly legislates, approves budgets, and holds the government accountable, with the Prime Minister required to maintain its confidence. Elections follow a unique two-round system where a primary round narrows the field to two parties before the general election, ensuring a clear governing mandate.',
    address: 'Gyelyong Tshokhang, Thimphu',
    established_year: 2008,
  },
  {
    name: 'National Library and Archives of Bhutan',
    slug: 'national-library-of-bhutan',
    category_slug: 'cultural-centers',
    dzongkhag_slug: 'thimphu',
    description: 'Housed in a traditional Bhutanese-style building, the National Library preserves the largest collection of Dzongkha and Tibetan-script texts in the country, including ancient Buddhist manuscripts, xylographic prints, and historical documents dating back several centuries. The collection numbers in the tens of thousands of volumes covering Buddhist philosophy, Bhutanese law, astrology, and medicine. The institution also serves as the national archives, maintaining government records and historical photographs, and is open to researchers and the public.',
    address: 'Pedzoe Lam, Thimphu',
    established_year: 1967,
    latitude: 27.4678, longitude: 89.6412,
  },
  {
    name: 'Royal Textile Academy',
    slug: 'royal-textile-academy',
    category_slug: 'cultural-centers',
    dzongkhag_slug: 'thimphu',
    description: 'Founded under the patronage of Queen Mother Sangay Choden Wangchuck to preserve Bhutan\'s 13 traditional arts (Zorig Chusum), with a focus on textile weaving — one of the most revered art forms in Bhutanese culture. The academy houses a museum with over 100 rare and antique textiles including kushuthara, aikapur, and other intricate weave patterns, some dating back several hundred years. It offers training programs for young weavers to master complex techniques such as supplementary warp pattern weaving unique to Bhutan.',
    address: 'Norzin Lam, Thimphu',
    established_year: 2001,
    latitude: 27.4661, longitude: 89.6387,
  },
]
